### ISSUE TITLE
Integration with nginx ingress?

### ISSUE THREAD

**Issue by pierreozoux** [costela/hcloud-ip-floater#6]
Hi, and thanks for your work.

I see you mention metallb, would this work with nginx ingress also?

If I understand correctly your controller, we just need to publish a svc kind LoadBalancer, and your controller takes care of the rest :)

If it is true, then I'll update the documentation with this possibility.

**Comment by costela** [comment]
Hi,

yes, assuming you already have a floating IP, a `LoadBalancer` service is all you need. Automatic floating IP creation is also something I've thought a bit about, but it's not in the works yet.

I'm not sure I understand your question about nginx ingress. If you mean "will my nginx ingress deployment work if I put a LB service in front of it?" then the answer is "yes".
If you mean "can I use ingress resources to control `hcloud-ip-floater`?" than "no". Ingress resources have a lot more info and don't quite map as well onto the floating IP solution. We _could_ theoretically support them, but I haven't yet seen a convincing use-case.

As for metalLB, you probably need it as well, but for a totally different reason: when `hcloud-ip-floater` attaches your floating IP to whatever node is running your pods, the node must somehow answer the IP packets addressed to it. You can either add the floating IPs address to all your nodes (via whatever configuration/provisioning management you have), *or* you can have metallb handle that for you with a [simple layer2 config](https://metallb.universe.tf/configuration/#layer-2-configuration).
Note that if you choose metalLB, you currently have to keep its config up-to-date with your existing floating IPs. If/when I get around to fixing #2, this annoyance will also be gone.

Hope that clears up your questions!

**Comment by pierreozoux** [comment]
Yes actually it does clarify :)

But for completeness, I'll rephrase.

# problem space

Given I run nginx ingerss on dedicated VMs, how can I make it HA.
The https 443 and 80 ports are exposed with host network.

# solution space

We need to use floating IPs, and in case an nginx ingress node goes down, we want this to switch over.

I think your controller is just doing what I need. I'll deploy it, deploy a service with the type load balancer that point to my nginx ingres, and configure the nodes with ansible to be able to welcome this floating IP. And I don't need yet another moving piece like metallb :) 
I'll give it a try next week and PR some doc.

Side question, what do you use to deploy kube on hetzner, just curious :)
We first tried with kube hetzner, then with kubeadm by hand, quieter happy this way, and now we try kubespray and well, it is a bit complicated for a kubeadm wrapper I find ;)

Anyway, thanks again for sharing this piece of code, I think we'll use it :)

**Comment by costela** [comment]
Just to be sure we don't have any misunderstanding: what do you mean with "dedicated VMs"? Are these just k8s nodes you've tainted in order to ensure only nginx-ingress runs on them? Or are you running ingress totally outside of k8s? If it's the latter, then I'm afraid your use-case is currently not supported (and is probably outside of `hcloud-ip-floater`'s scope).

OTOH, if you mean the former, then yes, everything should Just Work™. :smile: 

I currently provision my nodes with a pretty thin ansible wrapper around kubeadm. Also tried a few different options before, but current kubeadm fits my personal "high-level vs low-level" preference best. My second favorite option would probably be [k3s](https://github.com/rancher/k3s), especially for quick-and-dirty clusters (for POCs, etc)

**Comment by pierreozoux** [comment]
Yes, thèse are k8s dedicated VMs.
So it will just work.

Thanks again and have a nice weekend :)
