### ISSUE TITLE
Swarm and the old floater ip

### ISSUE THREAD

**Issue by dioptre** [costela/hcloud-ip-floater#7]
Hi there,

I noticed your other now deprecated project:
https://github.com/costela/hetzner-ip-floater

I actually preferred the old approach.

I just wrote this for swarm, and it allows me to setup clusters intuitively in seconds on swarm, that I much prefer over using the patched together k8 approach:
https://github.com/sfproductlabs/roo

I was wondering if:
- you added the floating address to each machine (so it was pre-set with all your floating IPs like using ```sudo ip addr add xxx.xxx.183.82 dev eth0```)
- if you did, whether you noticed irregularities in performance
- if you didn't what else you did? as the code just assigned the floating cloud on the hetzner api, not on the machine (did you use an additional bash script?) would love to know your thoughts....

Thanks for your help!
Andrew

**Comment by costela** [comment]
@dioptre yes, back then I just added my floating IPs to some private interface during privisioning (or via config management).
The only performance issues were caused by swarm's lack of pods: if you don't want to have your ingress run everywhere, than there's no way to ensure both the IP floater and the ingress land on the same node, and when they don't all your requests need one extra hop.

I've unarchived the old project, if you want to suggest any improvements over there, but since I'm not using swarm anymore, it won't get a lot of attention from me.

**Comment by dioptre** [comment]
Ah interesting, I use host networking and constraints to ensure the match up.

I saw it was already closed, so forked it and added to it already... 
https://github.com/sfproductlabs/floater

I'll also maintain a docker image here:
https://hub.docker.com/repository/docker/sfproductlabs/floater

So if you really want to close it I'm happy to look after it.

Thanks for the great work mate.
Andrew
